framework:
    messenger:
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 3
                    multiplier: 2

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default: []

        routing:
            'App\MessageBus\Messages\Message': async


